name: Release

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: samuelbartik
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate tags
        id: docker_tags
        uses: docker/metadata-action@v3
        with:
          images: |
            samuelbartik/orbital-sync
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
          labels: ${{ steps.docker_tags.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: samuelbartik
          password: ${{ secrets.DOCKERHUB_TOKEN }}
